### ISSUE TITLE
[create-default-webpack-mf]: error after updates

### ISSUE THREAD

**Issue by SvetlanaMuravlova** [ZephyrCloudIO/zephyr-examples#29]
**create-default-webpack-mf/app1**

`  "dependencies": {
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "@babel/core": "7.25.2",
    "@babel/preset-react": "7.24.7",
    "babel-loader": "9.1.3",
    "external-remotes-plugin": "^1.0.0",
    "html-webpack-plugin": "5.6.0",
    "webpack": "^5.94.0",
    "webpack-cli": "5.1.4",
    "webpack-dev-server": "5.1.0"
  }`

node v20.11.1

`Svetlana-Muravlova-MacBook-Pro:app1 muravlovasvetlana$ npm run build

> default_webpack_mf_first@1.0.0 build
> webpack --mode production

[webpack-cli] Failed to load '/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app1/webpack.config.js' config
[webpack-cli] Error:  ZEPHYR  Could not resolve remote entry points for urls: 

        - default-webpack-mf_second.zephyr-examples.svetlanamuravlova-examples

        Please build them with Zephyr first or add as Unmanaged applications.

        Note: you can read application uid as follows:
                 - default-webpack-mf_second - project.json 'name' field of remote application
                 - zephyr-examples - git repository name
                 - svetlanamuravlova-examples - git organization name

        Or join and ask question in our discord: https://zephyr-cloud.io/discord
      
    at resolve_remote_dependencies (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/node_modules/zephyr-webpack-plugin/dist/lib/dependency-resolution/resolve-remote-dependencies.js:19:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async configure (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/node_modules/zephyr-webpack-plugin/dist/lib/with-zephyr.js:18:9)
    at async loadConfigByPath (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app1/node_modules/webpack-cli/lib/webpack-cli.js:1406:27)
    at async WebpackCLI.loadConfig (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app1/node_modules/webpack-cli/lib/webpack-cli.js:1515:38)
    at async WebpackCLI.createCompiler (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app1/node_modules/webpack-cli/lib/webpack-cli.js:1781:22)
    at async WebpackCLI.runWebpack (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app1/node_modules/webpack-cli/lib/webpack-cli.js:1877:20)
    at async Command.<anonymous> (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app1/node_modules/webpack-cli/lib/webpack-cli.js:944:21)
    at async Command.parseAsync (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app1/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async Command.<anonymous> (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app1/node_modules/webpack-cli/lib/webpack-cli.js:1356:13)
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: default_webpack_mf_first@1.0.0 
npm ERR!   at location: /Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app1 
Svetlana-Muravlova-MacBook-Pro:app1 muravlovasvetlana$ git remote -v
origin  git@github.com:SvetlanaMuravlova/zephyr-examples.git (fetch)
origin  git@github.com:SvetlanaMuravlova/zephyr-examples.git (push)`
Notice git origin and `default-webpack-mf_second.zephyr-examples.svetlanamuravlova-examples`. I suppose it is some cache issue, cuz svetlanamuravlova-examples I've used at first. Or it doesn't change if origin is changed

**create-default-webpack-mf/app2**

`  "dependencies": {
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "@babel/core": "7.25.2",
    "@babel/preset-react": "7.24.7",
    "babel-loader": "9.1.3",
    "html-webpack-plugin": "5.6.0",
    "webpack": "^5.94.0",
    "webpack-cli": "5.1.4",
    "webpack-dev-server": "5.1.0"
  }`
node v20.11.1

`Svetlana-Muravlova-MacBook-Pro:app2 muravlovasvetlana$ npm run build

> default_webpack_mf_second@1.0.0 build
> webpack --mode production

 ZEPHYR   Hi svetlana_muravlova_valor-software_com-da55zezk6hf!
 ZEPHYR   Building to default_webpack_mf_second.zephyr-examples.svetlanamuravlova-examples#1
 ZEPHYR   Hi svetlana_muravlova_valor-software_com-da55zezk6hf!
 ZEPHYR   Building to default_webpack_mf_second.zephyr-examples.svetlanamuravlova-examples#2
/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/node_modules/zephyr-agent/dist/lib/upload/upload.js:10
        switch (options.uploadConfig.type) {
                                     ^

TypeError: Cannot read properties of undefined (reading 'type')
    at /Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/node_modules/zephyr-agent/dist/lib/upload/upload.js:10:38
    at Generator.next (<anonymous>)
    at /Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/node_modules/zephyr-agent/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/node_modules/zephyr-agent/node_modules/tslib/tslib.js:165:16)
    at upload (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/node_modules/zephyr-agent/dist/lib/upload/upload.js:8:20)
    at webpack_zephyr_agent (/Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/node_modules/zephyr-webpack-plugin/dist/lib/ze-agent/index.js:17:37)

Node.js v20.11.1
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: default_webpack_mf_second@1.0.0 
npm ERR!   at location: /Users/muravlovasvetlana/Documents/projects/zephyr-examples/examples/create-default-webpack-mf/app2 `

**Comment by SvetlanaMuravlova** [comment]
resolved
